Install requires pycryptodome, not pycrypto
PyCrypto version on PyPi is 2.6, but sjcl requires 2.7.
PyCrypto is not maintained. PyCryptodome is a drop in replacement.

A fresh install of sjcl with PyCrypto in Python 3.6.1 on macOS results
in error on:
  File "/Users/jthetzel/.local/src/py_test/venv/lib/python3.6/
  site-packages/sjcl/sjcl.py", line 76, in check_mode_ccm
    "You need a version >= 2.7a1 (or a special branch)."
  Exception: Pycrypto does not seem to support MODE_CCM.
  You need a version >= 2.7a1 (or a special branch).

A fresh install of sjcl with PyCryptodome has no error.